name=pdi-framework
version=1.3.1
author=Suraj I.
maintainer=Suraj I. <surajinamdar151@gmail.com>
sentence=Portable Device Interface (PDI) framework stack for easy configurable applications running over avr, esp8266, esp32 devices. Designed to easily manage services such as WiFi, HTTP/S, MQTT, SSH server, SFTP, Telnet server, OTA, GPIO, Serial, Commandline terminal and much more.
paragraph=pdi framework includes all services like gpio, wifi, cmd, mqtt, ntp, ota, napt, http/s server, telnet, ssh server, sftp, commandline terminal etc. which are ready to use in all applications where arduino, esp8266, esp32 devices will be used.
category=Other
url=https://github.com/Suraj151/pdi-framework
architectures=avr,esp8266,esp32
dot_a_linkage=true
