/*******************************************************************************
This file is part of the pdi stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : DeviceIotTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _DEVICEIOTTABLE_H_
#define _DEVICEIOTTABLE_H_

#include <database/core/DatabaseTable.h>

#define DEVICE_IOT_TABLE_ID 9

/**
 * @name    DeviceIotTable
 *
 * @purpose DeviceIot table handles iot configs load/store operations
 *
 */
class DeviceIotTable : public DatabaseTable<DEVICE_IOT_TABLE_ID, device_iot_config_table, 1, true>
{

  public:
  private:
  protected:
};

extern DeviceIotTable __device_iot_table;

#endif // _DEVICEIOTTABLE_H_
