/*******************************************************************************
This file is part of the pdi stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : LoginTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _LOGINTABLE_H_
#define _LOGINTABLE_H_

#include <database/core/DatabaseTable.h>

#define LOGIN_TABLE_ID 1

/**
 * @name    LoginTable
 *
 * @purpose Login table handles credential configs load/store operations
 *
 */
class LoginTable : public DatabaseTable<LOGIN_TABLE_ID, login_credential_table, 1, true>
{

  public:
  private:
  protected:
};

extern LoginTable __login_table;

#endif // _LOGINTABLE_H_
