/*******************************************************************************
This file is part of the pdi stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : MqttLwtTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _MQTTLWTTABLE_H_
#define _MQTTLWTTABLE_H_

#include <database/core/DatabaseTable.h>

#define MQTT_LWT_TABLE_ID 6

/**
 * @name    MqttLwtTable
 *
 * @purpose Mqtt Lwt table handles LWT configs load/store operations
 *
 */
class MqttLwtTable : public DatabaseTable<MQTT_LWT_TABLE_ID, mqtt_lwt_config_table, 1, false>
{

  public:
  private:
  protected:
};

extern MqttLwtTable __mqtt_lwt_table;

#endif // _MQTTLWTTABLE_H_
