/*******************************************************************************
This file is part of the pdi stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : MqttGeneralTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _MQTTGENERALTABLE_H_
#define _MQTTGENERALTABLE_H_

#include <database/core/DatabaseTable.h>

#define MQTT_GENERAL_TABLE_ID 5

/**
 * @name    MqttGeneralTable
 *
 * @purpose MqttGeneral table handles general configs load/store operations
 *
 */
class MqttGeneralTable : public DatabaseTable<MQTT_GENERAL_TABLE_ID, mqtt_general_config_table, 1, true>
{

  public:
  private:
  protected:
};

extern MqttGeneralTable __mqtt_general_table;

#endif // _MQTTGENERALTABLE_H_
