/*******************************************************************************
This file is part of the pdi stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : MqttPubSubTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _MQTTPUBSUBTABLE_H_
#define _MQTTPUBSUBTABLE_H_

#include <database/core/DatabaseTable.h>

#define MQTT_PUBSUB_TABLE_ID 7

/**
 * @name    MqttPubSubTable
 *
 * @purpose Mqtt PubSub table handles publish & subscribe topic configs load/store operations
 *
 */
class MqttPubSubTable : public DatabaseTable<MQTT_PUBSUB_TABLE_ID, mqtt_pubsub_config_table, 1, false>
{

  public:
  private:
  protected:
};

extern MqttPubSubTable __mqtt_pubsub_table;

#endif // _MQTTPUBSUBTABLE_H_
