/*******************************************************************************
This file is part of the pdi stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : OtaTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _OTATABLE_H_
#define _OTATABLE_H_

#include <database/core/DatabaseTable.h>

#define OTA_TABLE_ID 3

/**
 * @name    OtaTable
 *
 * @purpose OTA table handles ota server configs load/store operations
 *
 */
class OtaTable : public DatabaseTable<OTA_TABLE_ID, ota_config_table, 1, false>
{

  public:
  private:
  protected:
};

extern OtaTable __ota_table;

#endif // _OTATABLE_H_
