/*******************************************************************************
This file is part of the pdi stack.

This is free software. you can redistribute it and/or modify it but without any
warranty.

File            : WiFiTable.h
Author          : Suraj I.
created Date    : 1st Jan 2024

Note            : THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
*******************************************************************************/

#ifndef _WIFITABLE_H_
#define _WIFITABLE_H_

#include <database/core/DatabaseTable.h>

#define WIFI_TABLE_ID 2

/**
 * @name    WiFiTable
 *
 * @purpose Wifi table handles wifi configs load/store operations
 *
 */
class WiFiTable : public DatabaseTable<WIFI_TABLE_ID, wifi_config_table, 1, true>
{

  public:
  private:
  protected:
};

extern WiFiTable __wifi_table;

#endif // _WIFITABLE_H_
